from plugins.bubblellaneous.internal.category import Category
from plugins.bubblellaneous.internal.unit.base import Base
from plugins.bubblellaneous.registry.food import (
    Broccoli,
    Burger,
    Cheese,
    ChocolateBar,
    CoffeeCup,
    Cucumber,
    Donut,
    Grapes,
    Omelette,
    Toast,
    Tomato,
)
from plugins.bubblellaneous.registry.furniture import *
from plugins.bubblellaneous.registry.miscellaneous import (
    ArrowDownRoadSign,
    ArrowLeftRoadSign,
    ArrowRightRoadSign,
    ArrowUpRoadSign,
    Box,
    CallBell,
    Hatch,
    MossyTrafficBarrier,
    NoEntranceRoadSign,
    ParkRoadSign,
    Pole,
    TrafficBarrier,
    WindowBoards,
)
from plugins.bubblellaneous.registry.technology import *

REGISTRY: list[Base] = [
    BubbleBench(Category.FURNITURE),
    Table(Category.FURNITURE),
    Shelf(Category.FURNITURE),
    Cabinet(Category.FURNITURE),
    Drawer(Category.FURNITURE),
    Cupboard(Category.FURNITURE),
    Bench(Category.FURNITURE),
    Couch(Category.FURNITURE),
    Stool(Category.FURNITURE),
    Barstool(Category.FURNITURE),
    DinningChair(Category.FURNITURE),
    Blinds(Category.FURNITURE),
    KitchenCabinet(Category.FURNITURE),
    Fridge(Category.FURNITURE),
    Washer(Category.FURNITURE),
    Trashcan(Category.FURNITURE),
    TableLamp(Category.FURNITURE),
    StreetLight(Category.FURNITURE),
    DeskLamp(Category.FURNITURE),
    UpholsteryCouch(Category.FURNITURE),
    FloorLamp(Category.FURNITURE),
    Curtains(Category.FURNITURE),
    # ------
    Ladder(Category.TECHNOLOGY),
    PadlockBlock(Category.TECHNOLOGY),
    RisingDoor(Category.TECHNOLOGY),
    Pipe(Category.TECHNOLOGY),
    Radiator(Category.TECHNOLOGY),
    SurveillanceCamera(Category.TECHNOLOGY),
    SecurityMonitor(Category.TECHNOLOGY),
    Padlock(Category.TECHNOLOGY),
    Key(Category.TECHNOLOGY),
    # ------
    WindowBoards(Category.MISCELLANEOUS),
    Hatch(Category.MISCELLANEOUS),
    TrafficBarrier(Category.MISCELLANEOUS),
    MossyTrafficBarrier(Category.MISCELLANEOUS),
    Pole(Category.MISCELLANEOUS),
    NoEntranceRoadSign(Category.MISCELLANEOUS),
    ParkRoadSign(Category.MISCELLANEOUS),
    ArrowUpRoadSign(Category.MISCELLANEOUS),
    ArrowDownRoadSign(Category.MISCELLANEOUS),
    ArrowLeftRoadSign(Category.MISCELLANEOUS),
    ArrowRightRoadSign(Category.MISCELLANEOUS),
    Box(Category.MISCELLANEOUS),
    CallBell(Category.MISCELLANEOUS),
    # ------
    CoffeeCup(Category.FOOD),
    Cucumber(Category.FOOD),
    Grapes(Category.FOOD),
    Burger(Category.FOOD),
    Toast(Category.FOOD),
    Tomato(Category.FOOD),
    Cheese(Category.FOOD),
    ChocolateBar(Category.FOOD),
    Donut(Category.FOOD),
    Broccoli(Category.FOOD),
    Omelette(Category.FOOD),
]
