from plugins.bubblellaneous.internal.category import Category
from plugins.bubblellaneous.internal.unit.base import Base
from plugins.bubblellaneous.registry.food import *
from plugins.bubblellaneous.registry.furniture import *
from plugins.bubblellaneous.registry.miscellaneous import *
from plugins.bubblellaneous.registry.technology import *

REGISTRY: list[Base] = [
    BubbleBench(Category.FURNITURE),
    Table(Category.FURNITURE),
    Shelf(Category.FURNITURE),
    Cabinet(Category.FURNITURE),
    Drawer(Category.FURNITURE),
    Cupboard(Category.FURNITURE),
    Bench(Category.FURNITURE),
    Couch(Category.FURNITURE),
    Stool(Category.FURNITURE),
    Barstool(Category.FURNITURE),
    DinningChair(Category.FURNITURE),
    Blinds(Category.FURNITURE),
    KitchenCabinet(Category.FURNITURE),
    Fridge(Category.FURNITURE),
    Washer(Category.FURNITURE),
    Trashcan(Category.FURNITURE),
    TableLamp(Category.FURNITURE),
    StreetLight(Category.FURNITURE),
    DeskLamp(Category.FURNITURE),
    UpholsteryCouch(Category.FURNITURE),
    FloorLamp(Category.FURNITURE),
    Curtains(Category.FURNITURE),
    Sink(Category.FURNITURE),
    Toilet(Category.FURNITURE),
    # ------
    Ladder(Category.TECHNOLOGY),
    PadlockBlock(Category.TECHNOLOGY),
    RisingDoor(Category.TECHNOLOGY),
    Pipe(Category.TECHNOLOGY),
    Radiator(Category.TECHNOLOGY),
    SurveillanceCamera(Category.TECHNOLOGY),
    SecurityMonitor(Category.TECHNOLOGY),
    Padlock(Category.TECHNOLOGY),
    Key(Category.TECHNOLOGY),
    KeypadLock(Category.TECHNOLOGY),
    RetinaScanner(Category.TECHNOLOGY),
    ItemScanner(Category.TECHNOLOGY),
    Computer(Category.TECHNOLOGY),
    Calculator(Category.TECHNOLOGY),
    AlarmBlock(Category.TECHNOLOGY),
    LaserBlock(Category.TECHNOLOGY),
    Nanoglasses(Category.TECHNOLOGY),
    Crowbar(Category.TECHNOLOGY),
    Flashlight(Category.TECHNOLOGY),
    Battery(Category.TECHNOLOGY),
    MotionSensor(Category.TECHNOLOGY),
    ElectricalBox(Category.TECHNOLOGY),
    SafeBlock(Category.TECHNOLOGY),
    # ------
    WindowBoards(Category.MISCELLANEOUS),
    Hatch(Category.MISCELLANEOUS),
    TrafficBarrier(Category.MISCELLANEOUS),
    MossyTrafficBarrier(Category.MISCELLANEOUS),
    Pole(Category.MISCELLANEOUS),
    NoEntranceRoadSign(Category.MISCELLANEOUS),
    ParkRoadSign(Category.MISCELLANEOUS),
    ArrowUpRoadSign(Category.MISCELLANEOUS),
    ArrowDownRoadSign(Category.MISCELLANEOUS),
    ArrowLeftRoadSign(Category.MISCELLANEOUS),
    ArrowRightRoadSign(Category.MISCELLANEOUS),
    Box(Category.MISCELLANEOUS),
    CallBell(Category.MISCELLANEOUS),
    VendingMachine(Category.MISCELLANEOUS),
    Megaphone(Category.MISCELLANEOUS),
    Cup(Category.MISCELLANEOUS),
    Clipboard(Category.MISCELLANEOUS),
    Plate(Category.MISCELLANEOUS),
    Speakers(Category.MISCELLANEOUS),
    AlarmClock(Category.MISCELLANEOUS),
    Umbrella(Category.MISCELLANEOUS),
    BearTrap(Category.MISCELLANEOUS),
    PlayingCard(Category.MISCELLANEOUS),
    # ------
    CoffeeCup(Category.FOOD),
    Cucumber(Category.FOOD),
    Grapes(Category.FOOD),
    Burger(Category.FOOD),
    Toast(Category.FOOD),
    Tomato(Category.FOOD),
    Cheese(Category.FOOD),
    ChocolateBar(Category.FOOD),
    Donut(Category.FOOD),
    Broccoli(Category.FOOD),
    Omelette(Category.FOOD),
    Strawberry(Category.FOOD),
    Cereal(Category.FOOD),
    BeerBottle(Category.FOOD),
]
